# Generated by Django 4.2.7 on 2023-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_image_alter_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
