# Generated by Django 4.2.7 on 2023-11-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='amount_text',
            field=models.TextField(null=True),
        ),
    ]
