# Generated by Django 4.2.7 on 2023-11-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_amount_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='join immediately', null=True),
        ),
    ]
